name: puppeteer-master
description: Run Puppeteer web scraper in headless mode with Node.js
author: jexniemi
inputs:
  index_file_path:
    description: 'index.js file path'
    required: true
    
runs:
  using: 'composite'
  steps:
    - name: Pull Docker image
      run: docker pull ghcr.io/browserless/chromium
      shell: bash
    - name: Run Docker container
      run: docker run -p 3000:3000 ghcr.io/browserless/chromium
      shell: bash
    - name: Copy Node.js app files
      run: |
        node ${{ inputs.index_file_path }}
      shell: bash