name: puppeteer-master
description: Run Puppeteer web scraper in headless mode with Node.js
author: jexniemi
inputs:
  package_json_dir:
    description: 'Directory of package.json'
    required: true
  index_file_dir:
    description: 'Directory of index.js'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Pull Docker image
      run: docker pull ghcr.io/puppeteer/puppeteer:16.1.0
      shell: bash
    - name: Run Docker container
      run: docker run --init --cap-add=SYS_ADMIN --rm -d --name puppeteer_container ghcr.io/puppeteer/puppeteer:16.1.0
      shell: bash
    - name: Create /app directory in Docker container
      run: docker exec puppeteer_container mkdir -p /app
      shell: bash
    - name: Copy Node.js app files
      run: |
        docker cp "${{ inputs.package_json_dir }}/package.json" puppeteer_container:/app
        docker cp ${{ inputs.index_file_dir }}/* puppeteer_container:/app
      shell: bash
    - name: Install Node.js dependencies
      run: docker exec puppeteer_container bash -c "cd /app && npm install --production"
      shell: bash
    - name: Run index.js
      run: docker exec puppeteer_container bash -c "node /app/index.js"
      shell: bash