name: browserless-action-runner
description: Perform headless browser automation tasks (e.g. Puppeteer or Playwright web scraping) using browserless/chromium.
author: jexniemi
inputs:
  start_commands:
    description: 'Start commands to run'
    required: true
    
runs:
  using: 'composite'
  steps:
    - name: Run input commands
      run: |
        while IFS= read -r cmd; do
          eval "$cmd"
        done <<< "${{ inputs.start_commands }}"
      shell: bash

branding:
  icon: aperture
  color: blue