name: puppeteer-master
description: Run Puppeteer web scraper in headless mode with Node.js
author: jexniemi
inputs:
  app_dir:
    description: 'Directory of package.json'
    required: true
    
runs:
  using: 'composite'
  steps:
    - name: Pull Docker image
      run: docker pull ghcr.io/puppeteer/puppeteer:23.1.0
      shell: bash
    - name: Run Docker container
      run: docker run --init --cap-add=SYS_ADMIN --rm -d --name puppeteer_container ghcr.io/puppeteer/puppeteer:23.1.0
      shell: bash
    - name: Copy Node.js app files
      run: |
        docker cp ${{ inputs.app_dir }}/ puppeteer_container:/
      shell: bash
    - name: Check node version
      run: docker exec puppeteer_container node -v
      shell: bash
    - name: Run index.js
      run: docker exec puppeteer_container bash -c "node index.js"
      shell: bash