name: browserless-action-runner
description: Run Puppeteer or Playwright web scraper in headless mode
author: jexniemi
inputs:
  start_commands:
    description: 'Start commands to run'
    required: true
    
runs:
  using: 'composite'
  steps:
    - name: Pull Docker image
      run: docker pull ghcr.io/browserless/chromium:v2.18.0
      shell: bash
    - name: Run Docker container
      run: docker run --rm -p 3000:3000 --name browserless_container ghcr.io/browserless/chromium:v2.18.0 &
      shell: bash
    - name: Run input files
      run: |
        IFS=',' read -ra cmds <<< "${{ inputs.start_commands }}"
        for cmd in "${cmds[@]}"; do
          eval $cmd
        done
      shell: bash
    - name: Stop Docker container
      run: docker stop puppeteer_container
      shell: bash