name: Test Puppeteer Action

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run Puppeteer Action
      uses: ./ # Assumes the action is in the root directory of the repository
      with:
        package_json_dir: './example' # Replace with the directory of your package.json
        index_file_dir: './example' # Replace with the directory of your index.js