name: Test Puppeteer Action

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "18"

    - name: Install dependencies
      run: cd example && npm install --production

    - name: Run Puppeteer Action
      uses: ./ # Assumes the action is in the root directory of the repository
      with:
        index_file_path: './example/index.js' # Replace with the directory of your package.json